services:
  bot:
    image: bot:v1.1
    restart: always
    platform: linux/arm64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - files_data:/app/filesRepository
    env_file:
      ./.env
    depends_on:
      - db
      - files
    ports:
      - "${BOT_PORT_HOST}:${BOT_PORT_CONTAINER}"
  db:
    image: mongo:7
    restart: unless-stopped
    env_file:
      ./.env
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"
    volumes:
      - mongo_data:/data/db
  files:
    image: nginx:alpine
    restart: unless-stopped
    env_file:
      ./.env
    volumes:
      - files_data:/usr/share/nginx/html:ro
    ports:
      - "${FILE_PORT_HOST}:${FILE_PORT_CONTAINER}"

volumes:
  mongo_data:
  files_data: